import type { Medicine } from '../types';
import { isoDaysFromToday } from '../lib/date';

export function buildSeedMedicines(): Medicine[] {
  return [
    {
      id: 'seed-1',
      name: 'Amoxicillin 500mg',
      supplier: 'Emzor Pharmaceuticals',
      category: 'Antibiotics',
      quantity: 40,
      minQuantityThreshold: 20,
      expiryDate: isoDaysFromToday(-30),
      price: 1500,
    },
    {
      id: 'seed-2',
      name: 'Paracetamol Syrup 120ml',
      supplier: 'Fidson Healthcare',
      category: 'Analgesics',
      quantity: 25,
      minQuantityThreshold: 10,
      expiryDate: isoDaysFromToday(-5),
      price: 800,
    },
    {
      id: 'seed-3',
      name: 'Ibuprofen 400mg',
      supplier: 'GSK Nigeria',
      category: 'Analgesics',
      quantity: 60,
      minQuantityThreshold: 15,
      expiryDate: isoDaysFromToday(12),
      price: 1200,
    },
    {
      id: 'seed-4',
      name: 'Cetirizine 10mg',
      supplier: 'Sun Pharma',
      category: 'Antihistamines',
      quantity: 80,
      minQuantityThreshold: 20,
      expiryDate: isoDaysFromToday(25),
      price: 950,
    },
    {
      id: 'seed-5',
      name: 'Metformin 850mg',
      supplier: 'Cipla',
      category: 'Other',
      quantity: 3,
      minQuantityThreshold: 20,
      expiryDate: isoDaysFromToday(400),
      price: 2200,
    },
    {
      id: 'seed-6',
      name: 'Atorvastatin 20mg',
      supplier: 'Pfizer',
      category: 'Cardiovascular',
      quantity: 5,
      minQuantityThreshold: 15,
      expiryDate: isoDaysFromToday(280),
      price: 3500,
    },
    {
      id: 'seed-7',
      name: 'Loratadine 10mg',
      supplier: 'Sun Pharma',
      category: 'Antihistamines',
      quantity: 4,
      minQuantityThreshold: 12,
      expiryDate: isoDaysFromToday(20),
      price: 1100,
    },
    {
      id: 'seed-8',
      name: 'Vitamin C 1000mg',
      supplier: 'Emzor Pharmaceuticals',
      category: 'Vitamins',
      quantity: 200,
      minQuantityThreshold: 30,
      expiryDate: isoDaysFromToday(540),
      price: 600,
    },
    {
      id: 'seed-9',
      name: 'Multivitamin Complex',
      supplier: 'Fidson Healthcare',
      category: 'Vitamins',
      quantity: 90,
      minQuantityThreshold: 20,
      expiryDate: isoDaysFromToday(365),
      price: 1800,
    },
    {
      id: 'seed-10',
      name: 'Ciprofloxacin 500mg',
      supplier: 'Cipla',
      category: 'Antibiotics',
      quantity: 70,
      minQuantityThreshold: 25,
      expiryDate: isoDaysFromToday(180),
      price: 2400,
    },
    {
      id: 'seed-11',
      name: 'Azithromycin 250mg',
      supplier: 'Pfizer',
      category: 'Antibiotics',
      quantity: 45,
      minQuantityThreshold: 15,
      expiryDate: isoDaysFromToday(220),
      price: 3200,
    },
    {
      id: 'seed-12',
      name: 'Acyclovir 400mg',
      supplier: 'GSK Nigeria',
      category: 'Antivirals',
      quantity: 35,
      minQuantityThreshold: 10,
      expiryDate: isoDaysFromToday(300),
      price: 2800,
    },
    {
      id: 'seed-13',
      name: 'Omeprazole 20mg',
      supplier: 'Sun Pharma',
      category: 'Gastrointestinal',
      quantity: 110,
      minQuantityThreshold: 25,
      expiryDate: isoDaysFromToday(450),
      price: 1400,
    },
    {
      id: 'seed-14',
      name: 'Salbutamol Inhaler',
      supplier: 'GSK Nigeria',
      category: 'Respiratory',
      quantity: 22,
      minQuantityThreshold: 8,
      expiryDate: isoDaysFromToday(420),
      price: 4500,
    },
    {
      id: 'seed-15',
      name: 'Aspirin 75mg',
      supplier: 'Emzor Pharmaceuticals',
      category: 'Cardiovascular',
      quantity: 150,
      minQuantityThreshold: 30,
      expiryDate: isoDaysFromToday(600),
      price: 500,
    },
    {
      id: 'seed-16',
      name: 'Diclofenac 50mg',
      supplier: 'Fidson Healthcare',
      category: 'Analgesics',
      quantity: 55,
      minQuantityThreshold: 20,
      expiryDate: isoDaysFromToday(330),
      price: 900,
    },
  ];
}
